# Generated by Django 5.1.7 on 2025-04-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(choices=[('CANDIDATE', 'CANDIDATE'), ('HIRER', 'HIRER')], default='HIRER', max_length=20),
        ),
    ]
