# Generated by Django 5.1.7 on 2025-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(choices=[('PATIENT', 'PATIENT'), ('DOCTOR', 'DOCTOR')], default='PATIENT', max_length=20),
        ),
    ]
