<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-11 09:18
=======
# Generated by Django 5.1.7 on 2025-04-11 11:14
>>>>>>> 35b17590b16ea3a0242962e138b259a7afd496d7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
<<<<<<< HEAD
            field=models.CharField(choices=[('PATIENT', 'PATIENT'), ('DOCTOR', 'DOCTOR')], default='PATIENT', max_length=20),
=======
            field=models.CharField(choices=[('PATIENT', 'PATIENT'), ('DOCTOR', 'DOCTOR'), ('CLINIC', 'CLINIC')], default='PATIENT', max_length=20),
>>>>>>> 35b17590b16ea3a0242962e138b259a7afd496d7
        ),
    ]
